nextcloud/app_api

.github/workflows/tests-deploy.yml
appinfo/info.xml
docs/deploy.md
lib/Command/Daemon/RegisterDaemon.php
lib/Command/ExApp/Deploy.php
lib/Command/ExApp/Register.php
lib/Db/ExApp.php
lib/Db/ExAppMapper.php
lib/Docker/DockerActions.php
lib/Migration/Version1000Date202305221555.php
lib/Service/AppEcosystemV2Service.php

Docker deploy tests

---

lib/Command/ExApp/Register.php
lib/Service/AppEcosystemV2Service.php

fix + small refactor

---

lib/Service/ExAppApiScopeService.php

added `files_sharing` scope

---

.github/workflows/docs-check.yml
.github/workflows/docs.yml
.github/workflows/lint-unrelated.yml
.github/workflows/lint.yml
.github/workflows/tests-deploy-unrelated.yml
.github/workflows/tests-deploy.yml
.github/workflows/tests-unrelated.yml
.github/workflows/tests.yml

Added status checks for branch-protection

---

appinfo/routes.php
lib/Controller/ExAppController.php
lib/Controller/OCSApiController.php
lib/Service/AppEcosystemV2Service.php
lib/Service/ExAppApiScopeService.php

Resolves: #35.
Return consistent ExApps list structure.

api adjustments

---

.github/workflows/lint.yml
appinfo/routes.php
lib/Command/ExApp/Enable.php
lib/Command/ExApp/Register.php
lib/Controller/ExAppController.php
lib/Controller/ExFileActionsMenuController.php
lib/Controller/OCSApiController.php
lib/Controller/OCSExAppController.php

Refactoring and cleanup. Added OCS API enable/disable ExApp

---

lib/Service/AppEcosystemV2Service.php

throttle when signature or data-hash is not valid
reset previous throttling (if any) after successful auth

Added throttling to authentication

---

lib/Service/ExAppApiScopeService.php

We still need ability to specify api scopes by name...

added `Talk` API scope group

---

.github/workflows/tests-deploy.yml
.github/workflows/tests-special.yml
.github/workflows/tests.yml
lib/Service/AppEcosystemV2Service.php

use nextcloud option allow_local_address=>true

---

lib/Service/ExFilesActionsMenuService.php

add instanceid to action file

---

.github/workflows/tests.yml

Or our tests was too old, or this change was lost in last merge somehow.

CI fix: added `TALK_BOT` scope

---

examples/to_gif__python/Dockerfile
examples/to_gif__python/Makefile
examples/to_gif__python/appinfo/info.xml
examples/to_gif__python/requirements.txt
examples/to_gif__python/src/main.py

initial commit, all except WebDav is done

to_gif without framework [example]

---

docs/tech_details/ApiScopes.rst
lib/Service/ExAppApiScopeService.php

added `ACTIVITIES` API scope

---

examples/to_gif__python/Makefile
examples/to_gif__python/requirements.txt
examples/to_gif__python/src/main.py

I did not test it after changes, but should work

adjusted example for last changes

---

docs/tech_details/Deployment.rst
lib/DeployActions/DockerActions.php

add APP_PERSISTENT_STORAGE env

---

lib/AppAPIAuthBackend.php

subj, currently they are not working with AppAPI auth.

fixed an url for CalDav, CardDav and other extension on top of WebDAV

---

docs/tech_details/ApiScopes.rst
lib/Service/ExAppApiScopeService.php

Just added a scope, this is not working now, as Notes app uses `CORS` annotation

added scope for Notes app

---

lib/Controller/ExAppsPageController.php
src/components/Apps/AppDetails.vue
src/components/Apps/ScopesDetails.vue
src/views/Apps.vue

Show ExApps manually deployed and registered in ExApps management UI.
Only enable/disable actions allowed.
This is temporal solution, will be reworked later with mixed apps concept.

list apps not registered in appstore

---

lib/Controller/ExAppsPageController.php
lib/DeployActions/DockerActions.php
lib/Fetcher/ExAppArchiveFetcher.php
lib/Service/AppAPIService.php
lib/Service/ExAppApiScopeService.php

Fix system flag env setup.
Added default algorithm of app release archive download and signature check.
Fix scopes check in some type of daemon configurations (sanitize ocs api url prefix)

added archive download and signature check as for default

---

lib/Service/ExAppApiScopeService.php

Users#getCurrentUser has `/cloud/user` url
Apps want to know information about current user =)

api_scope fix for provisioning_api:getCurrentUser

---

.github/workflows/tests-deploy.yml
.github/workflows/tests-special.yml
.github/workflows/tests.yml

Fix CI fails during "/init" in dev environment

---

.github/workflows/tests.yml
lib/Db/DaemonConfig.php
lib/Migration/Version1000Date202305221555.php

Related to #94
Currently only added a single test with MySQL

Support of Mysql database

---

Makefile
docs/ManagingExternalApplications.rst
docs/conf.py
docs/resources/css/styles.css
docs/tech_details/Deployment.rst
lib/DeployActions/DockerActions.php

removed "-e" flag in `register` and etc

adjusting docs for the new version

---

lib/Service/ExFilesActionsMenuService.php
package-lock.json
package.json
src/filesplugin.js

Add Nextcloud 28 file actions support

add new file action registration method support

---

docs/tech_details/Authentication.rst
docs/tech_details/InstallationFlow.rst
docs/tech_details/index.rst

PR available for corrections and additions

added `ExApp` installation flow docs

---

CHANGELOG.md
appinfo/info.xml
lib/Service/AppAPIService.php

here we forgot to swap the parameters

aeRequestToExApp fix, parameters should be swapped

---

docs/DeployConfigurations.rst
docs/tech_details/Deployment.rst

Resolves: #115
Since we have already described the deployment process in technical. documentation, just added a link to it from a more visible place.

docs: added clarification for remote execution of ExApps

---

lib/DeployActions/AIODockerActions.php
lib/DeployActions/DockerActions.php

Fix missing changes after GPU support adjustments.

fixes after gpu option changes, update default daemons with it

---

CHANGELOG.md
appinfo/info.xml

The ability for ExApps to draw the user interface will be left for the next version 1.4.0

Version 1.3.0

---

lib/Db/UI/FilesActionsMenuMapper.php
lib/Db/UI/InitialStateMapper.php
lib/Db/UI/ScriptMapper.php
lib/Db/UI/StyleMapper.php
lib/Db/UI/TopMenuMapper.php
lib/Migration/Version1003Date202311061844.php
lib/Service/UI/FilesActionsMenuService.php
src/filesplugin.js

Add support of multiple mimes in File Actions

---

CHANGELOG.md
appinfo/info.xml
lib/Migration/Version1004Date202311061844.php

We do not merge this until v1.4 is fully ready, just update it to not forget what we added in this release.

v1.4.0 Change log update

---

lib/DeployActions/AIODockerActions.php

use THIS_IS_AIO env to detect AIO installation

---

CHANGELOG.md
appinfo/info.xml

Maintenance update with updated nextcloud vue packages for NC28

v1.4.2 update

---

APPS.md
CHANGELOG.md
appinfo/info.xml

subj.
And we need to publish new version ASAP.

added link to Go example and new Talk Bot

---

docs/tech_details/InstallationFlow.rst

Old:
New:
Ref: https://github.com/cloud-py-api/app_api/issues/160

updated docs for "Enabled" endpoint in InstallationFlow

---

docs/tech_details/api/appconfig.rst
docs/tech_details/api/preferences.rst
lib/Controller/AppConfigController.php
lib/Controller/PreferencesController.php

Ref: #160
Corrected docs and fixed a small bug-typo in `PreferencesController::setUserConfigValue`

fixed docs for app-cfg and preferences-cfg

---

docs/tech_details/Authentication.rst

Ref: #181
Ref: https://github.com/nextcloud/server/pull/42479

docs: app_api session keys

---

lib/AppInfo/Application.php
lib/Controller/AppConfigController.php
lib/Controller/ConfigController.php
lib/Controller/DaemonConfigController.php
lib/Controller/ExAppsPageController.php
lib/Controller/NotificationsController.php
lib/Controller/OCSApiController.php
lib/Controller/OCSExAppController.php
lib/Controller/OCSUiController.php
lib/Controller/PreferencesController.php
lib/Controller/TalkBotController.php
lib/Controller/TopMenuController.php

removed old style attributes definitions

---

CHANGELOG.md
lib/DeployActions/DockerActions.php

fix ssl config check in deployConfig (#186)

---

lib/Service/ExAppApiScopeService.php

subj, nothing special.
ref: https://docs.nextcloud.com/server/latest/developer_manual/_static/openapi.html#/operations/settings-log_settings-download

added "Admin Log" route to the System API Scope

---

CHANGELOG.md
lib/Middleware/ExAppUiMiddleware.php

UI Proxy: support of cache buster in URLs

---

CHANGELOG.md
src/filesplugin.js

Partially related to: #179 (we'll implement separate optional multiple files handler later).

enh: implement execBatch for fileAction in NC28+

---

lib/Service/AppAPIService.php

requestToExApp: removed CURLStringFile

---

CHANGELOG.md
appinfo/info.xml
lib/DeployActions/DockerActions.php

And we publish a new version with this fix, as this error prevents to open AppAPI settings

Catch "Exception" to handle MalformedUriException

---

docs/CreationOfDeployDaemon.rst
docs/DeployConfigurations.rst
lib/DeployActions/AIODockerActions.php

adjusting deploy daemon docs for AppAPI 2.0

---

src/components/DaemonConfig/RegisterDaemonConfigModal.vue

fix(i18n): host name -> hostname

---

docs/DeployConfigurations.rst

added chapter: "NC to ExApp Communication"

---

lib/Service/ProvidersAI/TranslationService.php

added forgotten "task_id" param to ExApp

---

CHANGELOG.md
appinfo/info.xml
lib/Service/ProvidersAI/SpeechToTextService.php
lib/Service/ProvidersAI/TextProcessingService.php
lib/Service/ProvidersAI/TranslationService.php

We broke all AI providers in `2.0.0` version, this is a fix for that.

fix(ai_providers): use PublicFunctions to call to ExApp

---

Makefile

Subj, we forgot to change it there.

Makefile: `aa-docker-socket-proxy` to `nextcloud-appapi-dsp`

---

lib/Db/UI/FilesActionsMenuMapper.php
lib/Db/UI/TopMenuMapper.php
lib/Service/UI/FilesActionsMenuService.php
lib/Service/UI/TopMenuService.php

The same as in the #229 
_Let's make code cleaner!_

Optimize work with caches (UI API)

---

docs/tech_details/api/machinetranslation.rst
lib/Controller/TranslationController.php
lib/Db/Translation/TranslationProvider.php
lib/Migration/Version2200Date20240216164351.php
lib/Service/ProvidersAI/TranslationService.php

This PR introduces optional declaration of Translation provider handler for language detection from text.

feat(MachineTranslation): Add optional IDetectLanguageProvider implementation

---

lib/Db/ExAppMapper.php
lib/Service/ExAppService.php

subj, a little more code, but more secure when "MYSQL Server has gone away" error occurs

always reset cache during ExApp unregister

---

CHANGELOG.md
docs/tech_details/ApiScopes.rst
lib/Service/ExAppApiScopeService.php

subj.
Also removed from docs on that make mention of already removed `optional` Api Scopes.

added text-processing and translation api scopes

---

.github/workflows/tests-deploy.yml
CHANGELOG.md
tests/test_occ_commands_docker.py

_skeleton was moved to a separate repository in a previous week_

fixed url to app-skeleton

---

appinfo/info.xml
lib/DeployActions/DockerActions.php

fix of possible "undefined variable" error

---

.github/workflows/tests.yml
docs/tech_details/api/occ_command.rst
lib/Controller/OccCommandController.php
lib/Db/Console/ExAppOccCommand.php
lib/Db/Console/ExAppOccCommandMapper.php
lib/Db/ExAppEventsListenerMapper.php
lib/Db/SpeechToText/SpeechToTextProviderMapper.php
lib/Db/TextProcessing/TextProcessingProviderMapper.php
lib/Db/Translation/TranslationProvider.php
lib/Db/Translation/TranslationProviderMapper.php
lib/Db/UI/FilesActionsMenuMapper.php
lib/Db/UI/SettingsFormMapper.php
lib/Db/UI/TopMenuMapper.php
lib/Fetcher/ExAppArchiveFetcher.php
lib/Migration/Version2205Date20240411124836.php
lib/Service/ExAppOccService.php

Should fix incorrect type handling by different DBMS during ExApp occ command registration.

fix(occ): incorrect type of field in ExAppOccCommand

---

docs/DeployConfigurations.rst

Reference: https://github.com/cloud-py-api/docker-socket-proxy/issues/28#issuecomment-2168437920

Corrected DeployConfigurations.rst

---

lib/Controller/TopMenuController.php

This PR adds missing check for TopMenu entry registered only for admins.

fix(top_menu): add missing admin check if top_menu only for admin

---

lib/Service/AppAPIService.php

For every incoming request to the cloud, we do an extra read from the database.
For every outgoing request, we do the same.
Anyway, we haven’t used this thing once in a year; it’s easier to remove it than to transfer this flag to the ex_app table to optimize speed.

speed: removed debug logging to `aa_debug.log`

---

lib/AppInfo/Application.php

Maybe this will remove spam in the logs, and in any case it is a small optimization

register TaskProcessingProviders only for NC30+

---

docs/CreationOfDeployDaemon.rst
docs/DeployConfigurations.rst
docs/DevSetup.rst
docs/Installation.rst
docs/ManagingExternalApplications.rst
docs/TestDeploy.rst
docs/faq/DockerContainerRegistry.rst
docs/faq/DockerSocketProxy.rst
docs/faq/GpuSupport.rst
docs/faq/Scaling.rst
docs/faq/Troubleshooting.rst
docs/faq/index.rst
docs/index.rst
docs/notes_for_developers/DevelopmentEnvironment.rst
docs/notes_for_developers/ExAppDevelopmentSteps.rst
docs/notes_for_developers/ExAppLifecycle.rst
docs/notes_for_developers/ExAppOverview.rst
docs/notes_for_developers/index.rst
docs/tech_details/Authentication.rst
docs/tech_details/Deployment.rst
docs/tech_details/api/exapp.rst
docs/tech_details/api/index.rst
lib/Controller/OCSExAppController.php
lib/Migration/Version2800Date20240710220000.php
lib/PublicFunctions.php

Docs updates with known FAQ (will be updated with time) and some Notes for Developers as an overview or replacement of old parts of docs in future.

enh(docs): docs updates

---

lib/Service/ExAppEventsListenerService.php
lib/Service/ExAppOccService.php
lib/Service/ExAppService.php
lib/Service/ProvidersAI/SpeechToTextService.php
lib/Service/ProvidersAI/TaskProcessingService.php
lib/Service/ProvidersAI/TextProcessingService.php
lib/Service/ProvidersAI/TranslationService.php
lib/Service/UI/FilesActionsMenuService.php
lib/Service/UI/SettingsService.php
lib/Service/UI/TopMenuService.php

It's a refactoring, it doesn't really fix anything(?), but it makes working with caches in the style of a Nextcloud server repository.

ench: use distributed cache only when available

---

lib/DeployActions/DockerActions.php

Fix incorrect info logging, log after imageId change

fix(DockerActions): correct info log, move after imageId change

---

lib/DeployActions/DockerActions.php

```
Undefined variable $r at /var/www/html/apps/app_api/lib/DeployActions/DockerActions.php#249
```
during usual ExApp install that has not GPU images, only the basic one.

"Undefined variable $r" during ExApp installs

---

.github/workflows/appstore-build-publish.yml

Update appstore publish action, from now updates (for NC<30) will go through `nextcloud-releases`

chore: update appstore-build-publish.yml

---

appinfo/info.xml

Pin versions for shipped app since NC 30.0.1.

[stable30] chore: pin NC versions for shipped app since 30.0.1

---

.github/workflows/tests-deploy.yml
.github/workflows/tests-special.yml
.github/workflows/tests.yml

Update tests CI for main branch only

chore: update tests CI for main branch

---

.tx/backport

Prepare Transifex config with upcoming stable branches.

chore: update transifex backport branches

---

.tx/backport

Prepare Transifex config with upcoming stable branches.

[stable30] chore: update transifex config

---

.tx/backport

Prepare Transifex config with upcoming stable branches.

[stable29] chore: update transifex config

---

lib/Service/AppAPIService.php

Added stopping of docker containers when ExApp is disabling. Timeout of enable/disable increased to 60.
Manual backport of https://github.com/nextcloud/app_api/pull/430

Stopping of docker containers when ExApp is disabling. Backport.

---

lib/Service/AppAPIService.php

check healthcheck and heartbeat after ExApp container start [backport] [stable29]

---

lib/Migration/Version5000Date20241120135411.php

Fix https://github.com/nextcloud/app_api/issues/457

Fix migration for postgres support.

---

lib/Migration/Version5000Date20241120135411.php

[stable29] Fix migration for postgres support.

---

lib/Service/ExAppsPageService.php

[stable30] fix(initial-state): correct defaultDaemonConfig initial state

---

lib/Command/ExApp/Update.php

Manual backport of: https://github.com/nextcloud/app_api/pull/478

[stable30] fix(occ): correct app_api:app:update enabled state of ExApps, introduce helper options

---

.github/workflows/tests.yml

Manual backport of this PR: https://github.com/nextcloud/app_api/pull/556

[stable30] fix(CI): disable RateLimiting for Nextcloud in the CI
