nextcloud/app_api

- .gitignore
- README.md
- docs/definitions.rst
- docs/deploy/index.rst
- docs/development/index.rst
- docs/index.rst
- lib/Command/Daemon/RegisterDaemon.php
- lib/Command/ExApp/Deploy.php
- lib/Service/DaemonConfigService.php
> Dev: docs draft

- .github/workflows/docs-check.yml
- lib/Command/ExAppConfig/SetConfig.php
- lib/Db/ExAppConfigMapper.php
- lib/Middleware/AppEcosystemAuthMiddleware.php
- lib/Service/ExAppConfigService.php
> config command fixes, remove deprecated annotation reflector

- .github/workflows/tests.yml
- docs/api/index.rst
- docs/api/notifications.rst
- docs/index.rst
- lib/Command/ExApp/Deploy.php
- lib/Controller/NotificationsController.php
- lib/DeployActions/DockerActions.php
- lib/DeployActions/IDeployActions.php
- lib/DeployActions/ManualActions.php
- lib/Notifications/ExAppNotifier.php
- lib/Notifications/ExNotificationsManager.php
- lib/Service/ExAppApiScopeService.php
- lib/Service/ExFilesActionsMenuService.php
- src/filesplugin.js
> Notifications adjustments. DeployActions. Docs updates

- .github/workflows/tests-deploy.yml
- .github/workflows/tests-special.yml
- .github/workflows/tests.yml
As this was merged, we do not need Authentication patch anymore for Nextcloud core.
https://github.com/nextcloud/server/pull/39655
> removed AE auth patch for NC master branch

- .github/workflows/tests-deploy.yml
- .github/workflows/tests-special.yml
- .github/workflows/tests.yml
As this was merged, we do not need Authentication patch anymore for Nextcloud core(stable27).
nextcloud/server/pull/39799
> removed patches for stable27

- lib/Service/ExAppApiScopeService.php
added `/apps/files/ajax/` to `DAV` scope
Full route looks something like this: `/index.php/apps/files/ajax/download.php?dir=/Media`
This is not DAV, in the near future we need to separate scopes, as Calendar and other stuff uses DAV too, so `DAV` should be `FileSystem` or something like this.
Rebase on top of #40 to make CI pass.
> `/apps/files/ajax/` to `DAV` scope

- tests/app_version_higher.py
Last nc_py_api use `nc.notifications` instead of `nc.users.notifications`
> fixed test for last nc_py_api version

- .github/workflows/tests.yml
- README.md
- appinfo/info.xml
> Adjustments to release

- lib/DeployActions/AIODockerActions.php
- lib/DeployActions/DockerActions.php
- lib/Service/DaemonConfigService.php
- lib/Settings/Admin.php
- src/components/AdminSettings.vue
Resolves: #100 
Check only default daemon connection the same as in ExApps management page and show error note in admin settings.
> show error note if default daemon is not accessible

- docs/tech_details/api/index.rst
- docs/tech_details/api/other_ocs.rst
Added missing notes that it is possible to use other supported OCS APIs (mainly oriented for clients) for ExApps as we have separate authentication for that.
> Notes about possibility to use other OCS APIs with AppAPI

- lib/Controller/ExAppsPageController.php
- lib/Settings/Admin.php
When a daemon has been selected by default and then for some reason its configuration is missing from the DB, the AppAPI application becomes unusable from the UI.
_I came across this locally today._
> fixed UI error when default_daemon_config config missing

- Makefile
In my setup(when docker is listening on port) without `.local` in NC url I can not run examples installing them from the AppStore
Andrey, when you have time(it is not urgent) - please check with the new makefile on your side both stable27 and master NC, and if it works we can merge this.
> added domain name for `nextcloud-docker-dev` setup

- docs/DeployConfigurations.rst
- docs/resources/css/styles.css
Related to: #98 
Add security warning about Deploy daemon configuration and security
Removed Docker in Docker scheme as it is not recommended
Added to the examples recommended schemes with docker-socket-proxy
> add some security notes for admins

- lib/Migration/Version1000Date202305221555.php
Resolves: https://github.com/cloud-py-api/app_api/issues/116
For some reason it was not possible to do this by migration(I tried but got `tinytext` instead of `text`), but this is not particularly important, since this is more of a change for the future.
> change field to type 'TEXT' (no migration)

- .github/workflows/node-build.yml
- .github/workflows/tests-deploy.yml
- .github/workflows/tests.yml
- appinfo/info.xml
> added "stable28" branch

- lib/AppAPIAuthBackend.php
- lib/AppInfo/Application.php
- lib/Command/ExApp/Deploy.php
- lib/Command/ExApp/Register.php
- lib/Controller/ExAppsPageController.php
- lib/Controller/OCSApiController.php
- lib/DeployActions/AIODockerActions.php
- lib/DeployActions/DockerActions.php
- lib/Exceptions/AppAPIAuthNotValidException.php
- lib/Fetcher/AppAPIFetcher.php
- lib/Fetcher/ExAppArchiveFetcher.php
- lib/Fetcher/ExAppFetcher.php
- lib/Listener/UserDeletedListener.php
- lib/Middleware/AppAPIAuthMiddleware.php
- lib/Notifications/ExAppAdminNotifier.php
- lib/Notifications/ExAppNotifier.php
- lib/Notifications/ExNotificationsManager.php
- lib/Profiler/AppAPIDataCollector.php
- lib/Service/AppAPIService.php
- lib/Settings/Admin.php
Fixes IDE warnings:
* Qualifier can be replaced with an import
* Argument matches the parameter's default value
> cleanup: Qualifier -> Imports

- docs/tech_details/Deployment.rst
Subj. 
_I thought that this was already clear, but according to reviews, not everyone understands this, so it’s better to explicitly indicate it in the documentation_
@kyteinsky or should we also add this note in some other places?
> manual_install: added Note that deploy/start should be handled by dev

- .github/workflows/tests-deploy.yml
- .github/workflows/tests-special.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
- docs/ManagingExternalApplications.rst
- lib/Command/ExApp/Unregister.php
- lib/Service/AppAPIService.php
- tests/test_occ_commands_docker.py
Fixes #121
- small actions clean up
- added basic but very useful tests for "occ app_api:app:unregister"
Changes in behaviour:
- container of app is always removed
- volume  with data is removed by default, but optionally can be kept
- app_api does not try to disable ExApp if it is already disabled
- "--silent" options now means "max silence as possible"
- added "--force" option to ignore errors if any.
> occ app_api:app:unregister rework

- Makefile
- lib/Command/Daemon/RegisterDaemon.php
- lib/DeployActions/DockerActions.php
- src/components/Apps/DaemonDetails.vue
- src/components/DaemonConfig/DaemonConfigDetailsModal.vue
- src/components/DaemonConfig/RegisterDaemonConfigModal.vue
> Adjustments of NVIDIA GPU support in Docker containers

- .github/workflows/tests-deploy.yml
- appinfo/routes.php
- css/filesactions.css
- lib/AppInfo/Application.php
- lib/Controller/OCSUiController.php
- lib/Controller/TopMenuController.php
- lib/Db/UI/FilesActionsMenu.php
- lib/Db/UI/FilesActionsMenuMapper.php
- lib/Listener/LoadFilesPluginListener.php
- lib/Migration/Version1003Date202311061844.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppApiScopeService.php
- lib/Service/UI/FilesActionsMenuService.php
- lib/Service/UI/InitialStateService.php
- lib/Service/UI/ScriptsService.php
- lib/Service/UI/StylesService.php
- lib/Service/UI/TopMenuService.php
- src/filesplugin.js
* changed type of `order` to int in model
> UI: FileActions rework

- CHANGELOG.md
- lib/BackgroundJob/ExAppInitStatusCheckJob.php
> inverted ExApp `status.init_start_time` condition check

- lib/Service/DaemonConfigService.php
- src/components/DaemonConfig/RegisterDaemonConfigModal.vue
Ref: https://github.com/cloud-py-api/app_api/issues/153#issuecomment-1859634989
Small lazy check if `host` value starts from a protocol.
> added check of `host` value during daemon registration

- docs/tech_details/api/utils.rst
Old:
New:
Ref: https://github.com/cloud-py-api/app_api/issues/160
> updated docs for "api/v1/users" endpoint

- docs/tech_details/api/logging.rst
> updated docs for api/v1/log "log_lvl" param

- CHANGELOG.md
- lib/Command/Daemon/ListDaemons.php
- lib/Service/DaemonConfigService.php
- src/components/DaemonConfig/RegisterDaemonConfigModal.vue
- tests/test_occ_commands_docker.py
> fix: remove last slash in url

- CHANGELOG.md
- lib/Service/AppAPIService.php
@kyteinsky, please look, is this what you need or not.
If yes, then I will continue and finish it today.
Usage([php watch ref](https://php.watch/versions/8.1/CURLStringFile)):
```php
$txt = 'test content';
$txt_curlfile = new \CURLStringFile($txt, 'test.txt', 'text/plain');
$this->service->aeRequestToExAppById('appid', '/upload_file', '', 'POST', ['file' => $txt_curlfile, 'notes' => 'lol']);
```
Usage from Python backend([fastapi ref](https://fastapi.tiangolo.com/tutorial/request-files/#request-files)):
```python3
@APP.post("/upload_file")
def upload_file(file: UploadFile, notes: Annotated[str | None, Form()] = None):
print(notes)
if notes is None:
return responses.JSONResponse({"filename": file.filename, "size": file.size})
return responses.JSONResponse({"filename": file.filename, …
```
> requestToExApp: added CURLStringFile support

- CHANGELOG.md
- lib/Command/ExApp/Register.php
When someone accidentally register ExApp with `occ` without deploy it shows incorrect error, that leads to bug misunderstanding.
Found today during deployment with Benjamin.
> `occ app_api:app:register` error message

- .github/workflows/tests-deploy.yml
- CHANGELOG.md
- lib/DeployActions/DockerActions.php
- lib/Service/AppAPIService.php
The default daemon configuration (not including AIO, since we have a separate default configuration for AIO) sets:
* That all ExApp uses the host network interface
* That AppAPI refers to them by container name
This PR corrects the second point, so that AppAPI would contact ExApp via `localhost` in this case, because when `host` as network is used, the DNS for containers names does not work, and the container name cannot be accessed in any way.
**Also this PR adds a test for the default configuration.**
Changes in `buildExAppHost`:
```php
public function buildExAppHost(array $deployConfig): string {
if ((isset($deployConfig['net']) && $deployConfig['net'] !== 'host') || isset($deployConfig['host'])) {
return '0.0.0.0';
}
return '127.0.0.1';
}
```
**-->**	
```php
public function …
```
> do not bind all networks with `host` network on local daemon

- .github/workflows/tests.yml
During this PR(https://github.com/cloud-py-api/app_api/pull/184) we had found that in some cases we can broke the AppAPI Auth.
This PR adds check for this, as CORS bypassing is used for the Notes app to work and it is achieved by setting 'app_api' session key.
> CI: added installation of the Notes app

- lib/Service/UI/FilesActionsMenuService.php
- lib/Service/UI/TopMenuService.php
**Fixed getRegisteredFileActions/getExAppMenuEntries returning wrong result on first call**
_Issue was found during implementing SpeechToText Provider API, as this internal APIs has the same struct._
> Small bug in getRegisteredFileActions and getExAppMenuEntries

- .github/workflows/tests-special.yml
- CHANGELOG.md
- docs/tech_details/ApiScopes.rst
- lib/Middleware/AppAPIAuthMiddleware.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppApiScopeService.php
- tests/auth_scopes_system.py
- tests/psalm-baseline.xml
Added `ALL` ApiScope to allow the use of OCS Apis that we have not yet defined in the AppAPI.
Also with help of https://github.com/cloud-py-api/app_api/pull/190/commits/993a1113512ad0fad8aef61fc04b22460a4f7ad3 AppAPI now correctly returns status **401** instead of **996** for Controllers protected by AppAPIAuth attribute.
> `ALL` ApiScope

- lib/Command/ExApp/Register.php
If the `php occ app_api:app:register ... --info-xml` parameter is specified, then we should return an error if the file is not available for the specified parameter, rather than silently ignoring it.
_This is small fix, as this is used only for development we do not mention it in changelog._
> occ app:register -> return error if specified invalid info-xml

- lib/Command/Daemon/UnregisterDaemon.php
Looks like it was a typo during initial fast development, I did not find today any reason to perform a call
```php
$this->daemonConfigService->unregisterDaemonConfig($daemonConfig)
```
two times in a row.
> remove double "daemonConfigService->unregisterDaemonConfig" call

- lib/Command/Daemon/ListDaemons.php
- lib/Service/DaemonConfigService.php
Changed loglevel to debug(we should stick in all Services to loglevel `info` or `debug`).
It is used in 3 places, one place is already covered with log level, two more are in UI and it will visible in UI if returned array is empty.
> getRegisteredDaemonConfigs: always return array

- src/filesplugin.js
Fixing missed bug introduced in recent filesplugin update: when no icon set - FileAction is not registered in NC28.
> fix FileAction register logic depending on icon

- CHANGELOG.md
- appinfo/info.xml
- lib/Service/SpeechToTextService.php
- lib/Service/TextProcessingService.php
During PHP App registration process we don't have a complete session and other stuff queried from DI which is for some reason (I don't know why yet) breaks its usage later.
> delay userId querying from DI later in anonymous class

- lib/BackgroundJob/ExAppInitStatusCheckJob.php
- lib/Command/ExApp/Register.php
- lib/Controller/ExAppsPageController.php
- lib/Db/ExApp.php
- lib/Db/UI/InitialState.php
- lib/Service/AppAPIService.php
ExApp.php:
```php
$this->addType('status', 'string');
```
->
```php
$this->addType('status', 'json');
```
In DB we already have this field marked as json.
> ExApp status: do not encode & decode with hands

- CHANGELOG.md
- appinfo/info.xml
- lib/Controller/ExAppsPageController.php
- lib/DeployActions/DockerActions.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppService.php
More correct handling of the ExApps installation process when Nextcloud has a non-default directory location(e.g. `Unraid`):
```php
$occDirectory = null;
if (!file_exists("console.php")) {
$occDirectory = dirname(__FILE__, 5);
}
$this->logger->info(sprintf('Calling occ(directory=%s): %s', $occDirectory ?? 'null', $args));
$process = proc_open('php console.php ' . $args, $descriptors, $pipes, $occDirectory);
```
We first check if `occ` is available in the current directory, if yes, then we pass `null` to  proc_open.
On Unraid this works, as there half of Nextcloud directories are symlinks, and `occ` lives in current PHP directory, but not in the root of the Nextcloud.
Not sure how this will affect other installations, and will it break them or not, from what I see - it should not. …
> fixed errors found during installing on "Unraid"

- CHANGELOG.md
- docs/ManagingExternalApplications.rst
- docs/tech_details/Deployment.rst
- lib/Command/ExApp/Deploy.php
- lib/DeployActions/DockerActions.php
- lib/DeployActions/IDeployActions.php
- lib/DeployActions/ManualActions.php
All applications should, if they need to change their behavior depending on the config values in the Nextcloud, and not custom environment variables which we do not have the ability to set from the UI.
Let's remove this, because... it has never been used anywhere, and it is not at all clear why it was added..
> occ:app_api:app:deploy - remove `-e` option

- CHANGELOG.md
- lib/Controller/OCSApiController.php
We do not need it, as it is covered by `AppAPIAuth` already with correct checking for status['progress'] value.
> removed check for "enable" state in OCS "log"

- lib/Db/SpeechToText/SpeechToTextProviderMapper.php
- lib/Db/TextProcessing/TextProcessingProviderMapper.php
- lib/Db/Translation/TranslationProviderMapper.php
- lib/Service/ProvidersAI/SpeechToTextService.php
- lib/Service/ProvidersAI/TextProcessingService.php
- lib/Service/ProvidersAI/TranslationService.php
We don't need to have 2 caches for each provider, we only need one cache with the list enabled.
The cache with the general list was removed, as it is used only in the OCS API, which are called very rarely, and there it is not necessary, we will use caches only in those places where the execution time is critical (UI, internal APIs that are often called)
_Redis/ACPU will use less memory and overall this approach will be faster and less code_
> Optimize work with caches (AI providers)

- lib/Command/ExApp/Update.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppService.php
This will fix situations when ExApp after update or enabling work without errors, but state of previous error is still in DB and UI displays an error when all is already ok.
Also now we set 'error'(empty) always be present in "status" to allow us in future not check for it presence.
> reset "Error state" during Updating/Enabling of ExApp

- CHANGELOG.md
- lib/PublicFunctions.php
- lib/Service/AppAPIService.php
subj, we introduce it in AppAPI 2.0.0
> `exAppRequestWithUserInit` can accept empty `userId`

- lib/Service/DaemonConfigService.php
We missed that.
It is not an error, but just usual situation.
> changed loglvl from "error" to "debug"

- .github/workflows/tests-deploy.yml
Today we changed this parameter name in Docker Socket Proxy
Ref: https://github.com/cloud-py-api/docker-socket-proxy/pull/15
> EX_APPS_NET_FOR_HTTPS->EX_APPS_NET

- src/components/DaemonConfig/RegisterDaemonConfigModal.vue
At least for manual install, currently, a custom host is not saved as the front-end overwrites it which is quite confusing. 'host.docker.internal' is not resolvable under a Linux install of docker by default so it might make sense to not enforce this as a default setting in any case.
> Save user specified daemon host when using manual install

- CHANGELOG.md
- appinfo/info.xml
- lib/Middleware/AppAPIAuthMiddleware.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppService.php
1. In `AppAPIAuthMiddleware` we should check for `AUTHORIZATION-APP-API` header to not first perform request to DB.
2. In `validateExAppRequestToNC` we should do the same but for 'EX-APP-ID' header.
3. Removed debug log from `getExApp`, to not spam logs.
> Check for AppAPI Auth header

- CHANGELOG.md
- appinfo/info.xml
- lib/Notifications/ExAppAdminNotifier.php
> fix: check subject earlier before ExApp check

- .gitignore
- CHANGELOG.md
- lib/Service/ExAppService.php
Should significantly improve the performance of anything that uses the getExAppsList function:
1. Admin page
2. ExAppUIL10N middleware
3. And in many other places where there were multiple cyclic calls to `getExApp`
> ExApp caching: "exApp_"  -> "ex_apps"

- CHANGELOG.md
- lib/Command/ExApp/Register.php
- lib/Command/ExApp/Update.php
- lib/Db/ExApp.php
- lib/Db/ExAppMapper.php
- lib/Migration/Version2203Date20240325124149.php
- lib/Service/ExAppService.php
We do not read from written values, in two months we will drop separate table for ExApp scopes and rewrite reading of ApiScopes from the main table in one request, which will maximize performance.
> performance: store API scopes as a list in the main table

- CHANGELOG.md
- lib/Command/ExApp/Register.php
- lib/Command/ExApp/Update.php
They do almost the same like the original flags from Server repo with one difference:
`--showonly` flag can be specified only with `--all` flag.
We can not easy  make `--showonly` work for specified appid, cause we support updating ExApps with specifyng `json` or `xml` and not only by `appid`.
> added "all" and "showonly" flags to occ app:update

- CHANGELOG.md
- appinfo/info.xml
- lib/Service/ExAppService.php
Without this it just throws exception where nothing is clear, better to return correct error description.
> corrected error handling for occ:app:register and "update"

- CHANGELOG.md
- appinfo/info.xml
- appinfo/routes.php
- docs/tech_details/ApiScopes.rst
- docs/tech_details/api/events_listener.rst
- docs/tech_details/api/fileactionsmenu.rst
- docs/tech_details/api/index.rst
- lib/AppInfo/Application.php
- lib/Controller/EventsListenerController.php
- lib/Db/ExAppEventsListener.php
- lib/Db/ExAppEventsListenerMapper.php
- lib/Listener/FileEventsListener.php
- lib/Migration/Version2204Date20240401104001.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppApiScopeService.php
- lib/Service/ExAppEventsListenerService.php
- tests/psalm-baseline.xml
Node Events
***********
``node_event`` - events about File `Nodes`
Supported event sub-types:
* NodeCreatedEvent
* NodeTouchedEvent
* NodeWrittenEvent
* NodeDeletedEvent
* NodeRenamedEvent
* NodeCopiedEvent
> EventsListener API

- CHANGELOG.md
- lib/Service/AppAPIService.php
With PHP>=8.2 they will appear like this:
```
/var/www/html/apps-extra/app_api/lib/Service/AppAPIService.php
line 89
OCA\AppAPI\Service\AppAPIService->requestToExAppInternal(
[
"OCA\\AppAPI\\Db\\ExApp",
3
],
"POST",
"http://host.docker.internal:9031/video_to_gif",
[
"SensitiveParameterValue"
]
)
```
Also adjustments in the Nextcloud Server required, to hide headers in `IClient` calls, we cannot do it from AppAPI side.
> secrets appear on errors in logfile

- lib/BackgroundJob/ExAppInitStatusCheckJob.php
1. Removes spam about the same error every 5 minutes
2. If there is already some kind of error there, then do not overwrite it and do nothing
> fix: do not spam error, do not rewrite previous error

- CHANGELOG.md
- css/settings.css
- lib/Command/ExApp/Register.php
- lib/Command/ExApp/Update.php
- lib/DeployActions/DockerActions.php
- lib/Service/ExAppService.php
- src/mixins/AppManagement.js
- src/store/apps.js
Before this, we didn’t have a `healthcheck` at all, but instead there was simply a check to see if the container was running.
Checking whether the container is running has been moved to Deploy stage and now occurs at the end of the deployment process.
And between deployment and “init” there is now a correct health check.
Applications are not required to support healthcheck at all, so it is only checked if `['State']['Health']['Status']` is present.
Without a timeout, the timeout must be set by the application itself, as it is usually done for Docker containers healthcheck.
During a healthcheck, an application, for example, can now install some of its own packages or do something other with its docker container.
It should not communicate with the Nextcloud itself at this …
> initial support for Docker Healthcheck

- CHANGELOG.md
- docs/tech_details/InstallationFlow.rst
- lib/DeployActions/DockerActions.php
For the applications that uses "llama-cpp" it will be not enough to just reinstall PyTorch during "healthcheck"
In this case we allow authors to build custom images for ComputeDevice
> extra image pulling for selected "compute device"

- lib/Service/ExAppService.php
In our current code, `$appInfo['external-app']['scopes']['value']` is sometimes an array and sometimes not, depending on the data.
To ensure that `$appInfo['external-app']['scopes']` is always an array, even if it's just one value, we use the is_array() function to check the type and then adjust accordingly.
> fixed ExApp with one scope(llm2 for example) installation error

- docs/TestDeploy.rst
- lib/BackgroundJob/ExAppInitStatusCheckJob.php
- lib/Command/ExApp/Register.php
- lib/Command/ExApp/Update.php
- lib/Service/AppAPIService.php
- src/components/DaemonConfig/DaemonConfig.vue
- src/components/DaemonConfig/DaemonTestDeploy.vue
Test Deploy fixes, timeout logic adjustments, docs.
> Test deploy adjustments

- src/components/AdminSettings.vue
In the UI not proper key was used to set a config key.
Related to: #287
> fix incorrect init_timeout setting key

- src/adminSettings.js
- src/components/DaemonConfig/DaemonTestDeploy.vue
Set "Download ExApp logs" button availability depending on the "Test Deploy" step. Logs can be obtained only starting from "container_started" step, when the ExApp docker container is created.
Resolves: #286
> correct the logs availability UI state

- lib/Controller/ExAppProxyController.php
- lib/Service/AppAPIService.php
Currently cookies always rejected when ExApp is installed in DSP with `HTTPS` - this is now fixed.
> UIProxy: fixed incorrect the Domain of `cookie`

- CHANGELOG.md
- appinfo/info.xml
- src/components/DaemonConfig/RegisterDaemonConfigModal.vue
> fix(ui): add warning for http nextcloud url in https daemon

- CHANGELOG.md
- appinfo/info.xml
- src/components/DaemonConfig/DaemonTestDeploy.vue
Resolves: #299
Update `image_pull` and `init` progress in further status checks as well in test deploy modal.
> fix(ui): correct update of image_pull and init progress in test deploy

- lib/Controller/ExAppProxyController.php
We don't have to build the request data again, it's already original in 'php://input'
It is also better to send all headers.
Perhaps we don’t need the code with “buildMultipartFormData” either
> AppAPIProxy: send raw data and all headers to ExApp

- lib/Controller/ExAppProxyController.php
- tests/psalm-baseline.xml
Treat `PUT` with the same logic as `DELETE`
`$_POST` and `$_FILES` are always empty as PHP automatically does not parse data during `PUT`
Just send raw request which we received to ExApp.
> AppAPIProxy: fixed `PUT` requests processing with content

- lib/DeployActions/DockerActions.php
- lib/Service/AppAPIService.php
Ref: https://github.com/cloud-py-api/docker-socket-proxy/pull/33
> fix: preserve original Authentication to be swapped later in HaProxy

- lib/DeployActions/DockerActions.php
For convenience, we should have done this in UpperCase initially.
I will fix it in `nc_py_api` so that it is always converted before comparison, but this should also be unified on the AppAPI side
> always set COMPUTE_DEVICE in UpperCase

- lib/DeployActions/DockerActions.php
Before this, PR AppAPI only supported specifying Docker images in the following format:
* `ghcr.io/org-name/repostiry-name:tag`
* `ghcr.io/org-name/repostiry-name-{COMPUTE_DEVIСE_TYPE}:tag`
Specifying "COMPUTE_DEVIСE_TYPE" at the repository name level turned out to be very inconvenient:
* the standard `${{ secrets.GITHUB_TOKEN }}` from actions has access only to the repository, and to create actions for auto-publishing ExApps docker images, you had to create a custom github token for that
* these docker images with COMPUTE_DEVIСE_TYPE were not displayed as linked to repositories on GitHub, since adding COMPUTE_DEVIСE_TYPE occurred at the repository name level
Therefore, **starting with AppAPI 3.0**, I propose to move COMPUTE_DEVIСE_TYPE in the package version:
* …
> added support for new image docker name format

- src/components/DaemonConfig/DaemonConfigDetailsModal.vue
- src/components/DaemonConfig/ManageDaemonConfigModal.vue
- src/views/Apps.vue
1. Use link to AppAPI docs in ExApps management page
2. Use NcPasswordField for haproxy_password
> enh(ui): use link to docs and NcPasswordField

- .github/workflows/tests.yml
Add CI test with APCu enabled (ref: https://github.com/cloud-py-api/app_api/pull/348).
APCu test must fail on ExApp register step, and be resolved in linked PR.
> feat(ci): add test with APCu local cache enabled

- lib/Service/ExAppService.php
- tests/psalm-baseline.xml
We do not disable caches in other places as in CLI only `/ex_apps` cache is used.
Linked issue: https://github.com/cloud-py-api/app_api/issues/291
> fix: disable caching if APCu detected

- lib/Controller/ExAppProxyController.php
An external packet received by the proxy can have any value in 'X-Origin-IP' - we can't trust it, it's best to set it on our own
> fix: Proxy: do not trust input - always set own value for 'X-Origin-IP'

- lib/Controller/ExAppProxyController.php
- tests/psalm-baseline.xml
We forgot to change this in this PR: https://github.com/cloud-py-api/app_api/pull/277
For Proxy requests there should be no timeout, cause they are coming from user or external services and not from Nextcloud
Even if they will take a long time, Nextcloud instance will be not slow down
> Proxy: do not set timeout for requests to ExApp

- lib/Service/AppAPIService.php
1. Logs are written to a separate file
2. Log level - Warning
3. Only for those requests where "user" is set
Reference: https://github.com/nextcloud/server/pull/46539#pullrequestreview-2182378157
this is how logs look like:
```json
{"reqId":"t9ThOI2CheVn6sDUsUKO","level":2,"time":"2024-08-13T10:08:42+00:00","remoteAddr":"192.168.65.1","user":"admin","app":"nc_py_api","method":"GET","url":"/ocs/v1.php/cloud/capabilities?format=json","message":"impersonation request","userAgent":"python-httpx/0.25.2","version":"30.0.0.7","data":{"app":"nc_py_api"}}
{"reqId":"tVtHIEwQ5YKhbWUFTmKF","level":2,"time":"2024-08-13T10:08:42+00:00","remoteAddr":"192.168.65.1","user":"admin","app":"nc_py_api","method":"PROPFIND","url":"/remote.php/dav/files/admin","message":"impersonation …
```
> added logging of ExApp requests made on behalf of user

- lib/Controller/ExAppProxyController.php
> debug logging to the Proxy

- lib/Controller/ExAppProxyController.php
Yes, it changes the algorithm, but otherwise it does not work in PGSQL in production.
And so it is a little simpler, since the order of routes in `info.xml` is not important
> Proxy: check all routes until we find allowing route

- lib/Service/AppAPIService.php
This will require **one less network request** for each successful request from ExApp
> call `throttler->resetDelay` if only when delay present

- appinfo/info.xml
- docs/tech_details/api/routes.rst
- lib/Controller/ExAppProxyController.php
- lib/Db/ExAppMapper.php
- lib/Migration/Version3100Date20240822080316.php
```xml
<route>
<url>^api\/w\/nextcloud\/jobs\/.*</url>
<verb>GET,POST,PUT,DELETE</verb>
<access_level>PUBLIC</access_level>
<headers_to_exclude>[]</headers_to_exclude>
<bruteforce_protection>[401, 500]</bruteforce_protection>
</route>
```
Looks like this. ExApps should not implement its own protection, we should provide a way to enable basic protection from Nextcloud/AppAPI side.
> ability to enable bruteforce protection for ExApp routes

- lib/Db/TaskProcessing/TaskProcessingProvider.php
Found this when writing a small test for **nc_py_api**
without this change `$taskProcessingProvider->id` are always `null` 
```php
$taskProcessingProvider = $this->getExAppTaskProcessingProvider($appId, $name);
if ($taskProcessingProvider !== null) {
$this->mapper->delete($taskProcessingProvider);
$this->resetCacheEnabled();
return $taskProcessingProvider;
}
```
> fix: TaskProcessingAPI - unregister provider endpoint

- lib/Db/ExApp.php
- lib/Db/ExAppMapper.php
- lib/Migration/Version3200Date20240905080316.php
- lib/Service/AppAPIService.php
- lib/Service/ExAppService.php
Also drops no longer used field `api_scopes` from the DB
> removed not used `last_check_time` field

- CHANGELOG.md
- docs/ManagingExternalApplications.rst
- lib/Command/ExApp/Unregister.php
- tests/test_occ_commands_docker.py
Do not remove ExApp docker volume by default, deprecate old option `keep-data`, add new `rm-data` to remove ExApp data.
> fix(cli): do not remove persistent storage by default in ExApp unregister command

- CHANGELOG.md
- appinfo/routes.php
- docs/tech_details/api/exapp.rst
- lib/Controller/OCSExAppController.php
Added miscellaneous OCS method to get current Nextcloud instance base_url.
> feat: add nextcloud url helper info endpoint to get instance base_url

- docs/Installation.rst
- docs/faq/BehindCompanyProxy.rst
- docs/faq/index.rst
Should resolve these installation issues: https://github.com/nextcloud/app_api/issues/364 and https://github.com/nextcloud/app_api/discussions/371
> docs: FAQ - internet access is via a corporate proxy

- lib/Fetcher/AppAPIFetcher.php
- lib/Fetcher/ExAppFetcher.php
- tests/psalm-baseline.xml
After stable branches split we can update main branch for NC31 (after https://github.com/nextcloud/app_api/pull/399) with OCP changes (https://github.com/nextcloud/server/blob/master/lib/public/ServerVersion.php#L75-L81).
> fix(ex_app_fetcher): use new OCP ServerVersion

- .github/workflows/tests-deploy.yml
- .github/workflows/tests-special.yml
- .github/workflows/tests.yml
Update tests CI for stable29 branch only (NC 28 and 29)
> [stable29] chore(ci): update tests CI for stable29

- lib/Command/ExAppConfig/GetConfig.php
- Otherwise breaks with https://github.com/nextcloud/3rdparty/pull/1956
- So should be backported to stable30
> fix(command): Ensure that writeln() argument is string

- docs/requirements.txt
Fix docs CI by pining sphinx version to be lower than 8.x.x
> fix(docs): pin sphinx to <8 version

- lib/Service/AppAPIService.php
Resolves #384. If the checks still pass and this gets merged, perhaps we should take a look at other apps to see if they need to be updated in the same way.
> fix(AppAPIService): encode query parameter arrays via http_build_query

- .github/workflows/tests-deploy.yml
- lib/AppInfo/Application.php
- tests/test_occ_commands_docker.py
Also appid for "skeleton" is now "app-skeleton-python"
edited: juliushaertl -> juliusknorr
> renamed "cloud-py-api" to "nextcloud" for "app-skeleton-python" and "test-deploy"

- lib/Service/AppAPIService.php
If ExApp is resource-heavy, stopping it now does not always free up resources (only if it is implemented in ExApp itself, which is quite rare)
That is why we add this PR to turn off the docker container when clicking the "disable" button on ExApp.
With "manual installation" - nothing changes, we have nothing to turn off and this is not supported.
Also, the timeout for a request to ExApp to turn on/off has been raised from **30 seconds to 60 seconds**, which is still acceptable for UI so as not to seem slow;
Resolves: #410
> Added stopping of docker containers when ExApp is disabling. Timeout of enable/disable increased to 60.

- lib/Service/AppAPIService.php
After the previous PR(#430) which added stopping application containers feature when shutting down, as @andrey18106  correctly noted during our 1:1 conversation:
we cannot rely on the application inside the docker container to be ready to process the request at the moment the docker container is turned on.
This PR introduces handling of it by checking health-check and heartbeat.
> Fix: check healthcheck and heartbeat after ExApp container start

- lib/Service/AppAPIService.php
Manual backport of https://github.com/nextcloud/app_api/pull/436
> check healthcheck and heartbeat after ExApp container start [backport] [stable30]

- .github/workflows/docs-check.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/tests-deploy.yml
- .github/workflows/tests-special.yml
- .github/workflows/tests.yml
subj.
_CI is expected to fail, it is unrelated_
> updated actions/checkout to v4 and actions/upload-artifact to v4

- lib/Controller/DaemonConfigController.php
- lib/Service/DaemonConfigService.php
1. Since we need a password of at least 12 characters, we use `dummySecret123` instead of `dummySecret`
2. `checkDaemonConnection` expects to get the full Deploy Daemon configuration from the UI, so we get the password from the database if we get `dummySecret123` from the UI and the haproxy password is present in the database.
3. I added comments everywhere in the code
> (fix): do not expose haproxy password to UI

- lib/Service/ExAppsPageService.php
There is was missing check if no deploy daemons configured, null value produced warning logs.
Resolves: https://github.com/nextcloud/app_api/issues/472
> fix(initial-state): correct defaultDaemonConfig initial state

- lib/Command/ExApp/Update.php
Resolves: #474 
This PR corrects AppAPI `occ app_api:app:update` command logic in the following way:
1. By default disabled ExApps are not updated. Use option `--include-disabled` to update disabled ExApps too.
2. During update ExApp is enabled to perform initialization step, if it was disabled before update - by default it will be disabled after update.
> fix(occ): correct `app_api:app:update` enabled state of ExApps, introduce helper options

- appinfo/info.xml
The `stable31` branch was created yesterday, so the current version in the `main` branch now belongs to Nextcloud 32.
> (chore): bump version for Nextcloud 32

- appinfo/info.xml
> info.xml: replaced "cloud-py-api" with "nextcloud"

- .github/workflows/tests-deploy.yml
- appinfo/info.xml
- appinfo/routes.php
- lib/Command/ExApp/Register.php
- lib/Command/ExApp/Update.php
- lib/Controller/ExAppsPageController.php
- lib/Db/ExAppDeployOption.php
- lib/Db/ExAppDeployOptionsMapper.php
- lib/DeployActions/DockerActions.php
- lib/Migration/Version032001Date20250115164140.php
- lib/Service/ExAppDeployOptionsService.php
- lib/Service/ExAppService.php
- lib/Service/ExAppsPageService.php
Related to: #406
Requires: https://github.com/nextcloud/server/pull/50230
1. Envs (during update removed envs - removed, present envs preserve previous values, new envs set with default values or empty)
2. Mounts (bind host folders to ExApp container readwrite/readonly)
> feat: advanced deploy options

- lib/Service/ProvidersAI/TaskProcessingService.php
> enh(TaskProcessingService): Cache result of getRegisteredTaskProcessingProviders

- lib/Service/ExAppService.php
fixes #507 
CI passed due to multiple env vars in info.xml of the test app. Issue happens when there is only one.
> fix: correct env var parsing when there is only one entry

- lib/DeployActions/DockerActions.php
* Check local socket by assuming it starts with a slash
* Improve error logging for ping and deploy
Addresses #498 
Log messages now look like this when doint a ping via UI (if either the docker socket is not writable or the file path doesn't exist)
*socket doesn't exist*:
*socket is not writable*:
Also the frontend dialog for the deployment now shows
*deployment error for local socket*:
*deployment error for nextcloud DSP*:
Unfortunately I didn't find a way to get rid of the slightly misleading error message that - in case the socket is not usable - curl will always complain about not being able to connect tho `http://localhost/`, even though it's not using any http under the hood but trying to access the UNIX socket directly. When using curl in socket mode ( `CURLOPT_UNIX_SOCKET_PATH`), …
> Improve error logging

- lib/Controller/ExAppsPageController.php
* According to https://github.com/nextcloud/server/commit/9e327a5890735d2a4dc3b7f88ab5fd571119c21d#diff-e69a8a7fe6497b2b323e5b1247790347fc614a007e88ef017bad764781591ffbL413
Currently, when forcing the activation of an app ("Allow untested app"), the following error is thrown:
```
{"reqId":"X3sNgVxzk6cwfqJqYEmk","level":3,"time":"2025-02-13T20:28:00+00:00","remoteAddr":"172.24.0.1","user":"admin","app":"index","method":"POST","url":"/index.php/apps/app_api/apps/force","message":"Call to undefined method OC\\App\\AppManager::ignoreNextcloudRequirementForApp() in file '/var/www/html/apps/app_api/lib/Controller/ExAppsPageController.php' line 448","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 …
```
> Fix AppManager method name

- lib/Fetcher/ExAppArchiveFetcher.php
- lib/Service/AppAPIService.php
* Fix for #517
* Filters empty `occ` commandline params
* Adds improved logging in case this ever happens again (it was pretty hard to find the bug because after the `occ` command has been sent, nothing could be found in the logs)
**Notes**
* I was only able to reproduce this on NC31 (because I didn't find any NC32 compatible apps in the store, yet). So the base for this fix is `stable31`
* I took the liberty of defaulting `$this->config->getSystemValue('apps_paths')` with `[]`, because I found some errors in my logs when trying to uninstall an app (something like "foreach needs an array, string given ..."). This happens if `app_paths` is not set. `getSystemValue` will return an "empty" string in that case. 
* If possible, a testcase should be added for this. Maybe with any deployed app …
> Fix parameter preparation for occ command

- lib/Controller/ExAppProxyController.php
Just added the `content-length` header to the removal list in AppAPI before sending the request to the ExApp.
GuzzleClient will fill it itself.
Fixes: #536
> (fix): AppAPI Proxy - invalid "content-length"

- lib/Controller/OCSSettingsController.php
- lib/Controller/TaskProcessingController.php
- lib/Service/ExAppService.php
This code was written and needed when AppAPI was not tightly coupled with the server.
> chore: removed unnecessary code for old NCs

- lib/AppInfo/Application.php
- lib/Listener/LoadMenuEntriesListener.php
- lib/Service/UI/TopMenuService.php
- tests/psalm-baseline.xml
Results for 5k requests:
OCS call, AppAPI enabled(before PR):
```
Maximum request time: 0.01429 seconds
Minimum request time: 0.01301 seconds
Average request time: 0.01395 seconds
```
OCS call, AppAPI enabled(after PR):
```
Maximum request time: 0.01383 seconds
Minimum request time: 0.01281 seconds
Average request time: 0.01347 seconds (3.5% performance boost compared to old code)
```
_For frontend calls the speed is almost the same, slight boost with less then 1%, when two ExApps define their icons._
```php
$menuEntries = Server::get(TopMenuService::class)->getExAppMenuEntries();
...
/** @var IGroupManager $groupManager */
$groupManager = Server::get(IGroupManager::class);
/** @var INavigationManager $navigationManager */
$navigationManager = Server::get(INavigationManager::class);
/** …
```
> (fix): perfomance - load ExApps menu items only when event is triggered

- lib/AppInfo/Application.php
- lib/Listener/GetTaskProcessingProvidersListener.php
- lib/Service/ProvidersAI/TaskProcessingService.php
- tests/psalm-baseline.xml
Related PR: https://github.com/nextcloud/server/pull/52050
> (fix): use the event for AppAPI to get list of AI providers

- lib/BackgroundJob/ExAppInitStatusCheckJob.php
- lib/Command/Daemon/ListDaemons.php
- lib/Command/ExApp/Register.php
- lib/Controller/ConfigController.php
- lib/Controller/DaemonConfigController.php
- lib/DeployActions/AIODockerActions.php
- lib/DeployActions/DockerActions.php
- lib/Service/ExAppsPageService.php
- lib/Settings/Admin.php
- lib/SetupChecks/DaemonCheck.php
`IConfig->getAppValue` has been marked as deprecated since Nextcloud 29.
1. Replaced its usage with `IAppConfig->getValueString` where it was useful.
2. Marked `init_timeout` and `default_daemon_config` as lazy loading config options.
> chore: replaced deprecated "IConfig" methods with "IAppConfig"

- lib/DeployActions/DockerActions.php
In this PR: #340 we introduced a new and correct name of docker images format for specifying extended ExApps versions, where `COMPUTE_DEVIСE_TYPE` was specified at the package version level.
It's time to deprecate the old format (*afaik, there should not be ExApps using it*):
`ghcr.io/org-name/repostiry-name-{COMPUTE_DEVIСE_TYPE}:tag` - which has been deprecated for a long time.
_We forgot to do this for Nextcloud 31, but we won't backport it._
> chore: removed support of old docker image format

- .github/workflows/tests.yml
We need this after changes in Server repo: https://github.com/nextcloud/server/pull/50905
The same as in this PR: https://github.com/cloud-py-api/nc_py_api/pull/350
> fix: disabled RateLimiting for Nextcloud in the CI

- lib/Db/ExAppMapper.php
If ExApp have no `headers_to_exclude` specified in `info.xml`, this error spammed during install: `Undefined array key "headers_to_exclude" at /var/www/html/apps-extra/app_api/lib/Db/ExAppMapper.php#209 ` due to missing check. This PR resolves that.
> fix(exAppMapper): init missing headers_to_exclude

- lib/Controller/DaemonConfigController.php
- lib/Controller/ExAppsPageController.php
- lib/Service/AppAPIService.php
Fixes: #562 
_If backport will not fail, this should be backported, imho._
> fix(DeployDaemon): support for daemon names containing spaces

- .github/workflows/triage-question-flow.yml
Minor improvements to the algorithm when CI replaces the `question` label with `missing information` in the issues.
With this fix, `reminder_after_days` should pass after the last message **and** after the label `question` was assigned.
Without this fix, only the time since the last message is counted, which is not quite right and can lead to fast replacing `question` with `missing information` giving no time to reply to the issue author.
> fix(ci-action): consider label creation data in calculation

- lib/Controller/ExAppProxyController.php
Streaming did not work for me when using ex app routes and downloading a large file through them. Not sure if this is a correct or valid way to fix it, but it does allow downloading large files.
> fix: streaming

- appinfo/routes.php
- lib/Controller/OCSApiController.php
This is needed to resolve the following issue: https://github.com/nextcloud/context_agent/issues/46
The endpoint will be backported to Nextcloud 31.
You can test it with the following snippet:
```
print(nc.ocs("GET", f"{nc._session.ae_url}/info/nextcloud_url/absolute", json={"url": "some_url"}))
```
P.S. After we merge this, it might be a good idea to add a method to nc_py_api to allow calling it more cleanly.
> feat(new-route): added endpoint to call NC getAbsoluteURL

- lib/Notifications/ExAppNotifier.php
To avoid unnecessary work and logs
> fix(ExAppNotifier): First check if any exapps enabled
